// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6e1DIHkXj9uzGuryNHB6kFS4MJO5ei9Y',
    appId: '1:1081736422892:web:a5f171d460ca72b7d98cc9',
    messagingSenderId: '1081736422892',
    projectId: 'testes-10782',
    authDomain: 'testes-10782.firebaseapp.com',
    databaseURL: 'https://testes-10782-default-rtdb.firebaseio.com',
    storageBucket: 'testes-10782.appspot.com',
    measurementId: 'G-NMRBCNS0LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91r0qYWSX6Y9tm1-ruT0I_js1tcd3TRg',
    appId: '1:1081736422892:android:71e6e4ffc4edd164d98cc9',
    messagingSenderId: '1081736422892',
    projectId: 'testes-10782',
    databaseURL: 'https://testes-10782-default-rtdb.firebaseio.com',
    storageBucket: 'testes-10782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bt6_p4nCO3cCm0sLWiaoBrUN3JCuFVA',
    appId: '1:1081736422892:ios:de10b7157153ff03d98cc9',
    messagingSenderId: '1081736422892',
    projectId: 'testes-10782',
    databaseURL: 'https://testes-10782-default-rtdb.firebaseio.com',
    storageBucket: 'testes-10782.appspot.com',
    iosClientId: '1081736422892-btph0o10gr61c3hatnn3j6c218td6q56.apps.googleusercontent.com',
    iosBundleId: 'joao.ddm.example',
  );
}
