class ActionsList {
  static Map<String, String> actionsList = {
     "RRRP3" : "3 R Petroleum",
     "TTEN3" : "3tentos",
     "EALT3" : "Aco Altona",
     "EALT4" : "Aco Altona",
     "ADHM3" : "Advanced Dh",
     "AERI3" : "Aeris",
     "AESB3" : "Aes Brasil",
     "TIET11" : "Aes Tiete E",
     "TIET3" : "Aes Tiete E",
     "TIET4" : "Aes Tiete E",
     "AFLT3" : "Afluente T",
     "GRAO3" : "Agribrasil",
     "AGXY3" : "Agrogalaxy",
     "BRGE11" : "Alfa Consorc",
     "BRGE12" : "Alfa Consorc",
     "BRGE3" : "Alfa Consorc",
     "BRGE5" : "Alfa Consorc",
     "BRGE6" : "Alfa Consorc",
     "BRGE7" : "Alfa Consorc",
     "BRGE8" : "Alfa Consorc",
     "CRIV3" : "Alfa Financ",
     "CRIV4" : "Alfa Financ",
     "RPAD3" : "Alfa Holding",
     "RPAD5" : "Alfa Holding",
     "RPAD6" : "Alfa Holding",
     "BRIV3" : "Alfa Invest",
     "BRIV4" : "Alfa Invest",
     "ALSO3" : "Alianscsonae",
     "ALZR11" : "Alianza Trust Renda Imobiliaria Fundo Investimento Imobiliario",
     "AALR3" : "Alliar",
     "ALLD3" : "Allied",
     "ALPA3" : "Alpargatas",
     "ALPA4" : "Alpargatas",
     "APER3" : "Alper S.A.",
     "GOGL34" : "Alphabet DRN A",
     "AVLL3" : "Alphaville",
     "ALUP11" : "Alupar",
     "ALUP3" : "Alupar",
     "ALUP4" : "Alupar",
     "BAZA3" : "Amazonia",
     "ABEV3" : "Ambev S.A.",
     "AMBP3" : "Ambipar",
     "CBEE3" : "Ampla Energ",
     "ANIM3" : "Anima",
     "ARZZ3" : "Arezzo Indústria e Comércio S.A.",
     "ARML3" : "Armac",
     "ASAI3" : "Assai",
     "ATMP3" : "AtmaSA",
     "ATOM3" : "Atompar",
     "AURA33" : "Aura 360",
     "AZEV3" : "Azevedo",
     "AZEV4" : "Azevedo",
     "AZUL4" : "Azul S.A.",
     "BTOW3" : "B2W - Companhia Digital",
     "B3SA3" : "B3 S.A. - Brasil, Bolsa, Balcão",
     "BAHI3" : "Bahema",
     "BMGB4" : "Banco Bmg",
     "BBDC3" : "Banco Bradesco S.A.",
     "BBDC4" : "Banco Bradesco S.A.",
     "BBAS3" : "Banco do Brasil S.A.",
     "BRSR6" : "Banco do Estado do Rio Grande do Sul S.A.",
     "BIDI11" : "Banco Inter",
     "BIDI4" : "Banco Inter S.A.",
     "BIDI3" : "Banco Inter S.A.",
     "MODL4" : "Banco Modal",
     "MODL11" : "Banco Modal",
     "MODL3" : "Banco Modal",
     "BPAN4" : "Banco Pan",
     "SANB3" : "Banco Santander (Brasil) S.A.",
     "SANB11" : "Banco Santander (Brasil) S.A.",
     "BGIP3" : "Banese",
     "BGIP4" : "Banese",
     "BEES3" : "Banestes",
     "BEES4" : "Banestes",
     "BPAR3" : "Banpara",
     "BRSR3" : "Banrisul",
     "BRSR5" : "Banrisul",
     "BDLL3" : "Bardella",
     "BDLL4" : "Bardella",
     "BTTL3" : "Battistella",
     "BALM3" : "Baumer",
     "BALM4" : "Baumer",
     "BBPO11" : "BB Progressivo II Fundo de Investimento Imobiliario - FII",
     "BBSE3" : "BB Seguridade Participações S.A.",
     "BMOB3" : "Bemobi Tech",
     "BMKS3" : "Bic Monark",
     "BIOM3" : "Biomm",
     "BSEV3" : "Biosev",
     "BKBR3" : "Bk Brasil",
     "BLAU3" : "Blau",
     "SOJA3" : "Boa Safra",
     "BOAS3" : "Boa Vista",
     "BOBR3" : "Bombril",
     "BOBR4" : "Bombril",
     "BBRK3" : "Br Brokers",
     "BRML3" : "BR Malls Participações S.A.",
     "BRBI11" : "BR Partners",
     "BRPR3" : "Br Propert",
     "BRAP4" : "Bradespar S.A.",
     "BRAP3" : "Bradespar S.A.",
     "AGRO3" : "Brasilagro",
     "BRKM6" : "Braskem",
     "BRKM5" : "Braskem S.A.",
     "BRKM3" : "Braskem S.A.",
     "BSLI3" : "Brb Banco",
     "BSLI4" : "Brb Banco",
     "BRFS3" : "BRF S.A.",
     "BRIT3" : "BriSAnet",
     "BTLG11" : "BTG Pactual Logística",
     "BPAC11" : "Btgp Banco",
     "BPAC3" : "Btgp Banco",
     "BPAC5" : "Btgp Banco",
     "CXSE3" : "Caixa Seguri",
     "CAMB3" : "Cambuci",
     "CAML3" : "Camil Alimentos S.A.",
     "CRFB3" : "Carrefour Br",
     "CASN" : "CaSAn",
     "CASN3" : "CaSAn",
     "CASN4" : "CaSAn",
     "CBAV3" : "CBA",
     "CCRO3" : "CCR S.A.",
     "CEAB3" : "Cea Modas",
     "CEBR3" : "Ceb",
     "CEBR5" : "Ceb",
     "CEBR6" : "Ceb",
     "CEDO3" : "Cedro",
     "CEDO4" : "Cedro",
     "CEED3" : "Ceee D",
     "CEED4" : "Ceee D",
     "EEEL3" : "Ceee Gt",
     "EEEL4" : "Ceee Gt",
     "CEGR3" : "Ceg",
     "CLSC3" : "Celesc",
     "CLSC4" : "Celesc",
     "GPAR3" : "Celgpar",
     "CEPE3" : "Celpe",
     "CEPE5" : "Celpe",
     "CEPE6" : "Celpe",
     "MAPT3" : "Cemepe",
     "MAPT4" : "Cemepe",
     "ELET3" : "Centrais Elétricas Brasileiras S.A. - Eletrobras",
     "ELET6" : "Centrais Elétricas Brasileiras S.A. - Eletrobras",
     "CESP3" : "Cesp",
     "CESP5" : "Cesp",
     "CESP6" : "Cesp",
     "HGTX3" : "Cia. Hering",
     "CIEL3" : "Cielo S.A.",
     "CLSA3" : "ClearSAle",
     "CEEB3" : "Coelba",
     "CEEB5" : "Coelba",
     "COCE3" : "Coelce",
     "COCE5" : "Coelce",
     "COGN3" : "Cogna Educação S.A.",
     "CGAS3" : "Comgas",
     "CGAS5" : "Comgas",
     "LCAM3" : "Companhia de Locação das Américas",
     "SBSP3" : "Companhia de Saneamento Básico do Estado de São Paulo - SABESP",
     "CMIG3" : "Companhia Energética de Minas Gerais",
     "CMIG4" : "Companhia Energética de Minas Gerais",
     "CPLE6" : "Companhia Paranaense de Energia - COPEL",
     "CPLE3" : "Companhia Paranaense de Energia - COPEL",
     "CSNA3" : "Companhia Siderúrgica Nacional",
     "CALI3" : "Const A Lind",
     "CALI4" : "Const A Lind",
     "CSMG3" : "CopaSA",
     "CPLE5" : "Copel",
     "CORR4" : "Cor Ribeiro",
     "RLOG3" : "CoSAn Log",
     "CSAN3" : "Cosan S.A.",
     "CSRN3" : "Cosern",
     "CSRN5" : "Cosern",
     "CSRN6" : "Cosern",
     "CTNM3" : "Coteminas",
     "CTNM4" : "Coteminas",
     "CPFE3" : "CPFL Energia S.A.",
     "CRDE3" : "Cr2",
     "CRPG3" : "Cristal",
     "CRPG5" : "Cristal",
     "CRPG6" : "Cristal",
     "CSED3" : "Cruzeiro Edu",
     "HGLG11" : "CSHG Logistica - Fundo De Investimento Imobiliario",
     "CMIN3" : "Csnmineracao",
     "CARD3" : "Csu Cardsyst",
     "CURY3" : "Cury S/A",
     "CVCB3" : "CVC Brasil Operadora e Agência de Viagens S.A.",
     "CCPR3" : "Cyre Com Ccp",
     "CYRE3" : "Cyrela Brazil Realty S.A. Empreendimentos e Participações",
     "DMVF3" : "D1000 Vfarma",
     "DASA3" : "DaSA",
     "DESK3" : "Desktop",
     "PNVL3" : "Dimed",
     "PNVL4" : "Dimed",
     "DIRR3" : "Direcional",
     "DOHL3" : "Dohler",
     "DOHL4" : "Dohler",
     "DMMO3" : "Dommo",
     "DOTZ3" : "Dotz S.A.",
     "DTCY3" : "Dtcom Direct",
     "DTEX3" : "Duratex",
     "ECOR3" : "EcoRodovias Infraestrutura e Logística S.A.",
     "ENBR3" : "EDP - Energias do Brasil S.A.",
     "EKTR3" : "Elektro",
     "EKTR4" : "Elektro",
     "ELET5" : "Eletrobras",
     "ELMD3" : "Eletromidia",
     "LIPR3" : "Eletropar",
     "EMAE3" : "Emae",
     "EMAE4" : "Emae",
     "EMBR3" : "Embraer S.A.",
     "ENAT3" : "Enauta Part",
     "ECPR3" : "Encorpar",
     "ECPR4" : "Encorpar",
     "ENGI" : "EnergiSA",
     "ENGI11" : "EnergiSA",
     "ENGI3" : "EnergiSA",
     "ENGI4" : "EnergiSA",
     "ENMT3" : "EnergiSA Mt",
     "ENMT4" : "EnergiSA Mt",
     "ENEV3" : "Eneva",
     "EGIE3" : "Engie Brasil Energia S.A.",
     "ENJU3" : "Enjoei",
     "EQPA3" : "Eqtl Para",
     "EQPA5" : "Eqtl Para",
     "EQPA6" : "Eqtl Para",
     "EQPA7" : "Eqtl Para",
     "EQTL3" : "Equatorial Energia S.A.",
     "ESPA3" : "Espacolaser",
     "YDUQ3" : "Estácio Participações S.A.",
     "ALPK3" : "Estapar",
     "ESTR3" : "Estrela",
     "ESTR4" : "Estrela",
     "ETER3" : "Eternit",
     "EUCA3" : "Eucatex",
     "EUCA4" : "Eucatex",
     "EVEN3" : "Even",
     "BAUH4" : "Excelsior",
     "EZTC3" : "Eztec",
     "VRTA11" : "Fator Verita",
     "HTMX11" : "FD Invest Imob Hotel Maxinvest",
     "FHER3" : "Fer Heringer",
     "FESA3" : "FerbaSA",
     "FESA4" : "FerbaSA",
     "FLRY3" : "Fleury S.A.",
     "POWE3" : "Focus On",
     "FRAS3" : "Fras Le",
    
        "BPFF11" : "Fundo de Investimento Imobiliario - FII Brasil Plural Absoluto Fundo de Fundos",
     "RBRP11" : "Fundo Investimento Imobiliario Rbr Properties Fii",
     "GFSA3" : "GafiSA",
     "GSHP3" : "Generalshopp",
     "GEPA3" : "Ger Paranap",
     "GEPA4" : "Ger Paranap",
     "GOAU3" : "Gerdau Met",
     "GGBR3" : "Gerdau S.A.",
     "GGBR4" : "Gerdau S.A.",
     "NINJ3" : "Getninjas",
     "GOLL4" : "Gol Linhas Aéreas Inteligentes S.A.",
     "GPIV33" : "Gp Invest",
     "PCAR3" : "GPA Companhia Brasileira de Distribuição",
     "GPCP3" : "Gpc Part",
     "GGPS3" : "GPS",
     "CGRA3" : "Grazziotin",
     "CGRA4" : "Grazziotin",
     "GRND3" : "Grendene S.A.",
     "GMAT3" : "Grupo Mateus S.A.",
     "SBFG3" : "Grupo Sbf",
     "SOMA3" : "Grupo Soma",
     "GUAR3" : "Guararapes",
     "HBTS5" : "Habitasul",
     "HAGA3" : "Haga S/A",
     "HAGA4" : "Haga S/A",
     "HAPV3" : "Hapvida",
     "HBRE3" : "Hbr Realty",
     "HCTR11" : "Hectare CE Fundo de Investimento Imobiliário",
     "HGBS11" : "HEDGE Brasil Shopping Fundo de Investimento Imobiliario",
     "HFOF11" : "Hedge Top FOFII 3",
     "HBOR3" : "Helbor Empreendimentos S.A.",
     "HETA3" : "Hercules",
     "HETA4" : "Hercules",
     "HBSA3" : "Hidrovias",
     "HOOT4" : "Hoteis Othon",
     "HYPE3" : "Hypera S.A.",
     "IGBR3" : "Igb S/A",
     "IGTA3" : "Iguatemi Empresa de Shopping Centers S.A.",
     "PARD3" : "Ihpardini",
     "ROMI3" : "Inds Romi",
     "IDVL3" : "Indusval",
     "IDVL4" : "Indusval",
     "INEP3" : "Inepar",
     "INEP4" : "Inepar",
     "IFCM3" : "Infracomm",
     "INTB3" : "Intelbras",
     "GNDI3" : "Intermedica",
     "MEAL3" : "International Meal Company Alimentacao S.A.",
     "MYPK3" : "Iochpe-Maxion S.A.",
     "RANI3" : "Irani",
     "RANI4" : "Irani",
     "IRBR3" : "IRB-Brasil Resseguros S.A.",
     "BOVA11" : "iShares Ibovespa Fundo de Índice ETF",
    
        "IVVB11" : "iShares S&P 500 Fundo de Investimento - Investimento No Exterior",
     "ITUB4" : "Itaú Unibanco Holding S.A.",
     "ITUB3" : "Itaú Unibanco Holding S.A.",
     "ITSA4" : "Itaúsa - Investimentos Itaú S.A.",
     "ITSA3" : "Itausa - Investimentos Itau S.A.",
     "JBDU3" : "J B Duarte",
     "JBDU4" : "J B Duarte",
     "JALL3" : "Jallesmachad",
     "JBSS3" : "JBS S.A.",
     "JDCO34" : "JD COM DRN",
     "JPSA3" : "JereisSAti",
     "JHSF3" : "JHSF Participacoes S.A.",
     "JFEN3" : "Joao Fortes",
     "JOPA3" : "JoSApar",
     "JOPA4" : "JoSApar",
     "KLAS3" : "Kallas",
     "CTKA3" : "Karsten",
     "CTKA4" : "Karsten",
     "KEPL3" : "Kepler Weber",
     "KNRI11" : "KINEA Renda Imobiliária - Fundo de Investimento Imobiliário",
     "KLBN3" : "Klabin S/A",
     "KLBN4" : "Klabin S/A",
     "KLBN11" : "KLABIN S/A UNT N2",
     "LAVV3" : "Lavvi",
     "LLBI3" : "Le Biscuit",
     "LLBI4" : "Le Biscuit",
     "LLIS3" : "Le Lis Blanc",
     "LIGT3" : "Light S/A",
     "LINX3" : "Linx",
     "RENT3" : "Localiza Rent a Car S.A.",
     "LWSA3" : "Locaweb",
     "LOGG3" : "Log Com Prop",
     "LOGN3" : "Log In",
     "LAME3" : "Lojas Americ",
     "LAME4" : "Lojas Americanas S.A.",
     "AMAR3" : "Lojas MariSA",
     "LREN3" : "Lojas Renner S.A.",
     "LPSB3" : "Lopes Brasil",
     "LUPA3" : "Lupatech",
     "MDIA3" : "M. Dias Branco S.A. Indústria e Comércio de Alimentos",
     "MGLU3" : "Magazine Luiza S.A.",
     "MGEL4" : "Mangels Indl",
     "POMO3" : "Marcopolo",
     "POMO4" : "Marcopolo",
     "MRFG3" : "Marfrig Global Foods S.A.",
     "MATD3" : "Mater Dei",
     "MXRF11" : "Maxi Renda Fundo De Investimento Imobiliaro - FII",
     "MSPA3" : "Melhor Sp",
     "MSPA4" : "Melhor Sp",
     "CASH3" : "Meliuz",
     "MELK3" : "Melnick",
     "BMEB3" : "Merc Brasil",
     "BMEB4" : "Merc Brasil",
     "MERC3" : "Merc Financ",
     "MERC4" : "Merc Financ",
     "BMIN3" : "Merc Invest",
     "BMIN4" : "Merc Invest",
    
        "MFII11" : "Merito Desenvolvimento Imobiliario I FII - Fundo de Investimento Imobiliario",
     "MTIG4" : "Metal Iguacu",
     "LEVE3" : "Metal Leve",
     "FRIO3" : "Metalfrio",
     "GOAU4" : "Metalurgica Gerdau S.A.",
     "MTSA3" : "MetiSA",
     "MTSA4" : "MetiSA",
     "MILS3" : "Mills Estruturas e Servicos de Engenharia S.A.",
     "BEEF" : "Minerva",
     "BEEF3" : "Minerva",
     "MNPR3" : "Minupar",
     "MTRE3" : "Mitre Realty",
     "MMXM11" : "Mmx Miner",
     "MMXM3" : "Mmx Miner",
     "MBLY3" : "Mobly",
     "MOAR3" : "Mont Aranha",
     "MOSI3" : "Mosaico",
     "MDNE3" : "Moura Dubeux",
     "MOVI3" : "Movida Participacoes S.A.",
     "MRVE3" : "MRV Engenharia e Participações S.A.",
     "MLAS3" : "Multilaser",
     "MULT3" : "Multiplan Empreendimentos Imobiliários S.A.",
     "MNDL3" : "Mundial",
     "NTCO3" : "Natura &Co Holding S.A.",
     "NATU3" : "Natura Cosméticos S.A.",
     "NEOE3" : "Neoenergia",
     "NGRD3" : "Neogrid",
     "BNBR3" : "Nord Brasil",
     "NORD3" : "Nordon Met",
     "NUTR3" : "Nutriplant",
     "OPCT3" : "Oceanpact",
     "ODPV3" : "Odontoprev",
     "OIBR4" : "Oi",
     "OIBR3" : "Oi S.A.",
     "OMGE3" : "Omega Ger",
     "ORVR3" : "Orizon",
     "OSXB3" : "Osx Brasil",
     "OFSA3" : "Ourofino S/A",
     "PDTC3" : "Padtec",
     "PGMN3" : "Pague Menos",
     "PATI3" : "Panatlantica",
     "PATI4" : "Panatlantica",
     "PEAB3" : "Par Al Bahia",
     "PEAB4" : "Par Al Bahia",
     "PMAM3" : "Paranapanema",
     "PDGR3" : "Pdg Realt",
     "PETZ3" : "Pet Center Comércio e Participações S.A.",
     "RPMG3" : "Pet Manguinh",
     "BRDT3" : "Petrobras Distribuidora S.A.",
     "PETR4" : "Petróleo Brasileiro S.A. - Petrobras",
     "PETR3" : "Petróleo Brasileiro S.A. - Petrobras",
     "RECV3" : "Petrorecôncavo S.A.",
     "PRIO3" : "Petrorio",
     "PTNT3" : "Pettenati",
     "PTNT4" : "Pettenati",
     "PINE4" : "Pine",
     "PLPL3" : "Planoeplano",
     "PLAS3" : "Plascar Part",
     "FRTA3" : "Pomifrutas",
     "PSSA3" : "Porto Seguro S.A.",
     "PSVM11" : "Porto Vm",
     "PTBL3" : "Portobello",
     "POSI3" : "Positivo Tec",
     "PPLA11" : "Ppla",
     "PRNR3" : "Priner",
     "PFRM3" : "Profarma",
     "QUAL3" : "Qualicorp Consultoria e Corretora de Seguros S.A.",
     "LJQQ3" : "Quero Quero",
     "RADL3" : "Raia Drogasil S.A.",
     "RAIZ4" : "Raizen",
     "RAPT3" : "Randon Part",
     "RAPT4" : "Randon Part",
     "RBRR11" : "RBR Rendimento High Grade",
     "RCSL3" : "Recrusul",
     "RCSL4" : "Recrusul",
     "RDOR3" : "Rede D Or",
     "REDE3" : "Rede Energia",
     "RNEW11" : "Renova",
     "RNEW3" : "Renova",
     "RNEW4" : "Renova",
     "RSUL4" : "Riosulense",
     "RDNI3" : "Rni",
     "RBNS11" : "Rodobens",
     "RSID3" : "Rossi Resid",
     "RAIL3" : "Rumo S.A.",
     "SAPR11" : "Sanepar",
     "SAPR3" : "Sanepar",
     "SAPR4" : "Sanepar",
     "SNSY3" : "Sansuy",
     "SNSY5" : "Sansuy",
     "SNSY6" : "Sansuy",
     "SANB4" : "Santander Br",
     "CTSA3" : "Santanense",
     "CTSA4" : "Santanense",
     "STBP3" : "Santos Brp",
     "SCAR3" : "Sao Carlos",
     "SMTO3" : "Sao Martinho",
     "SLED3" : "Saraiva Livr",
     "SLED4" : "Saraiva Livr",
     "SHUL4" : "Schulz",
     "CSAB3" : "Seg Al Bahia",
     "CSAB4" : "Seg Al Bahia",
     "SEQL3" : "Sequoia Log",
     "SEER3" : "Ser Educa",
     "SIMH3" : "Simpar",
     "SQIA3" : "Sinqia S.A.",
     "SLCE3" : "Slc Agricola",
     "SMFT3" : "Smart Fit",
     "SMLS3" : "Smiles Fidelidade S.A.",
     "SOND3" : "Sondotecnica",
     "SOND5" : "Sondotecnica",
     "SOND6" : "Sondotecnica",
     "SGPS3" : "Springs",
     "AHEB3" : "Spturis",
     "AHEB5" : "Spturis",
     "AHEB6" : "Spturis",
     "SULA11" : "Sul America",
     "SULA3" : "Sul America",
     "SULA4" : "Sul America",
     "SUZB3" : "Suzano S.A.",
     "TAEE3" : "TaeSA",
     "TAEE4" : "TaeSA",
     "TASA3" : "Taurus Armas",
     "TASA4" : "Taurus Armas S.A.",
     "TRAD3" : "Tc",
     "TECN3" : "Technos",
     "TCSA3" : "Tecnisa S.A.",
     "TCNO3" : "Tecnosolo",
     "TCNO4" : "Tecnosolo",
     "TGMA3" : "Tegma",
     "TEGA3" : "Tegra Incorporadora",
     "TEKA3" : "Teka",
     "TEKA4" : "Teka",
     "TKNO4" : "Tekno",
     "TELB3" : "Telebras",
     "TELB4" : "Telebras",
     "VIVT3" : "Telef Brasil",
     "VIVT4" : "Telefônica Brasil S.A.",
     "TEND3" : "Tenda",
     "TXSA34" : "Terniumsa DRN",
     "TESA3" : "Terra Santa",
     "LAND3" : "TerraSAntapa",
     "TXRX3" : "Tex Renaux",
     "TIMS3" : "TIM S.A.",
     "SHOW3" : "Time For Fun",
     "TOTS3" : "TOTVS S.A.",
     "TFCO4" : "Track Field",
     "TRPL3" : "Tran Paulist",
     "TRPL4" : "Tran Paulist",
     "TAEE11" : "Transmissora Aliança de Energia Elétrica S.A.",
     "LUXM4" : "TreviSA",
     "TRIS3" : "Trisul",
     "TPIS3" : "Triunfo Part",
     "TRXF11" : "TRX Real State",
     "TUPY3" : "Tupy",
     "RECT11" : "UBS BR Office",
     "UGPA3" : "Ultrapar Participações S.A.",
     "UCAS3" : "UnicaSA",
     "UNIP3" : "Unipar",
     "UNIP5" : "Unipar",
     "UNIP6" : "Unipar",
     "USIM3" : "Usiminas",
     "USIM6" : "Usiminas",
     "USIM5" : "Usinas Siderúrgicas de Minas Gerais S.A.",
     "VALE3" : "Vale S.A.",
     "VLID3" : "Valid Solucoes S.A.",
     "VAMO3" : "Vamos",
     "LVBI11" : "VBI Losístico",
     "PVBI11" : "VBI Prime Properties",
     "VIIA3" : "Via Varejo S.A.",
     "VILG11" : "Vinci Logistica Fundo Investimento Imobiliario FII",
     "VITT3" : "Vittia Fertilizantes S.A.",
     "VIVA3" : "Vivara Participacoes S.A.",
     "VVEO3" : "Viveo",
     "VIVR3" : "Viver",
     "VULC3" : "Vulcabras",
     "LVTC3" : "Wdc Networks",
     "WEGE3" : "WEG S.A.",
     "WEST3" : "Westwing",
     "MWET3" : "Wetzel S/A",
     "MWET4" : "Wetzel S/A",
     "WHRL3" : "Whirlpool",
     "WHRL4" : "Whirlpool",
     "WSON33" : "Wilson Sons",
     "WIZS3" : "Wiz Solucoes e Corretagem de Seguros S.A.",
     "WLMM3" : "Wlm Ind Com",
     "WLMM4" : "Wlm Ind Com",
  };
}
